### ISSUE TITLE
Upgrade to CloudFlare API v4

### ISSUE THREAD

**Issue by hugojosefson** [hugojosefson/node-cloudflare-dynamic-dns#1]
This is just to remind me (or any contributor) to upgrade the code during this summer.

Received this automatic email today from CloudFlare:

---

_**Time to Migrate to CloudFlare API v4**_
_We’re reaching out because we noticed you’re using CloudFlare’s API v1. Starting November 9th, 2016 at noon Pacific Time (20:00 UTC), CloudFlare will no longer be supporting API v1._
_CloudFlare uses API v4 to power our customer dashboard, so unlike API v1, it has support for every single feature on CloudFlare. We've written extensive documentation to help you migrate from v1 to v4 available here:_
_[API v1 to v4 Migration Documentation](https://www.cloudflare.com/migrating-to-v4/)_

---

**Comment by hugojosefson** [comment]
Possible alternative approaches, implementations to check out:
- [ ] https://gist.github.com/larrybolt/6295160
- [ ] https://github.com/18augst/cloudflare-ddns/blob/master/index.coffee
- [ ] https://github.com/Metatavu/grunt-cloudflarev4/blob/master/tasks/cloudflare.js
- [x] https://www.npmjs.com/package/cloudflare

**Comment by FlorianWendelborn** [comment]
@hugojosefson I used the `cloudflare` package for a [custom dynamic DNS server](https://github.com/impequid/dynamic-dns) I wrote and I think it's most likely the best one out there. Especially since it's made and actively maintained by Cloudflare.

**Comment by hugojosefson** [comment]
Thanks for the input @dodekeract! I'll look at that one first then.

**Comment by hugojosefson** [comment]
Fixed with v3.0.0.
